### PR TITLE
Fix model loading issues

### LINKED ISSUE #24: incorrect model loading
Not all models seem to load correctly. Some sub messes appear to not be positioned correctly. You can use renderDoc or nvidia nsight to help locate the issue

### PR DESCRIPTION
**Pull request by wba6**
- **Basic lighting on models**
- **update texture loading**
- **Update basic-build.yml**
- **Update basic-build.yml**
- **Update weekly-multi-platform-build.yml**
- **Rename Model lighting shaders**
- **Add basic shaders**
- **Handle node transformations**
- **Handle node transformations**
- **Add model**
- **Add model**
- **Remove old model**
- **update models**
- **Remove extra model**
- **Update path**
- **Remove extra flag for assimp**
- **Update flags for assimp**
- **Remove extra model**
- **Remove extra model**
- **update model**
- **Refactor variables to allow for UV flip**

### CODE REVIEW

File: Agate/src/Agate/Rendering/OpenGl/Texture.cpp [hunk 1]
```diff
@@ -1,62 +1,142 @@
...
-#define STB_IMAGE_IMPLEMENTATION
-
-#include <stb_image.h>
-#include <Core/Logger.h>
+#define KHRONOS_STATIC
+#include <ktx.h>
 
 namespace Agate {
+
+// Function to create a normalized path with forward slashes
```
Comment (wba6) [inline Agate/src/Agate/Rendering/OpenGl/Texture.cpp]: I'm not sure how I feel about the free functions in this file maybe look over this again

File: Agate/src/Agate/Rendering/OpenGl/Texture.cpp [hunk 2]
```diff
@@ -1,62 +1,142 @@
...
+                std::cerr << "Failed to load KTX texture at path: " << normalizedPath << std::endl;
+                // Optionally, set a default texture or handle the error gracefully
+            }
         } else {
-            PRINTERROR("Texture failed to load at path: {}", m_path);
-            GLCall(glBindTexture(GL_TEXTURE_2D, 0));
-            stbi_image_free(data);
+            // Load standard image using SOIL2
+            if (!load_standard_texture(normalizedPath, m_textureID, m_target, m_width, m_height)) {
+                std::cerr << "Failed to load standard texture at path: " << normalizedPath << std::endl;
```
Comment (wba6) [inline Agate/src/Agate/Rendering/OpenGl/Texture.cpp]: Use agate logging for this

File: Agate/src/Agate/Rendering/OpenGl/Texture.cpp [hunk 3]
```diff
@@ -1,62 +1,142 @@
...
-            GLCall(glBindTexture(GL_TEXTURE_2D, 0));
+            : m_width(0), m_height(0), m_path(file), m_type("texture"), m_target(GL_TEXTURE_2D) {
+        std::string normalizedPath = create_normalized_path(directory, m_path);
+        std::filesystem::path filepath(normalizedPath);
+        std::string extension = to_lowercase(filepath.extension().string());
+
+        if (extension == ".ktx" || extension == ".ktx2") {
+            // Load KTX file using libktx
+            if (!load_ktx_texture(normalizedPath, m_textureID, m_target, m_width, m_height)) {
+                std::cerr << "Failed to load KTX texture at path: " << normalizedPath << std::endl;
```
Comment (wba6) [inline Agate/src/Agate/Rendering/OpenGl/Texture.cpp]: Agate logging

File: Agate/src/Agate/Rendering/ModelLoader.cpp [hunk 4]
```diff
@@ -1,10 +1,17 @@
...
 #include "ModelLoader.h"
 #include "Agate/Core/Logger.h"
 #include "glad/glad.h"
 #include "OpenGl/VertexArray.h"
 #include <utility>
-
+#include <filesystem>
+
+namespace fs = std::filesystem;
+glm::mat4 convertMatrix(const aiMatrix4x4 &matrix) {
```
Comment (wba6) [inline Agate/src/Agate/Rendering/ModelLoader.cpp]: Better way to do this?

File: Agate/src/Agate/Rendering/OpenGl/Texture.cpp [hunk 5]
```diff
@@ -1,62 +1,142 @@
...
+// Helper function to convert string to lowercase
+    std::string to_lowercase(const std::string& str) {
+        std::string lower = str;
+        std::transform(lower.begin(), lower.end(), lower.begin(),
+                       [](unsigned char c){ return std::tolower(c); });
+        return lower;
+    }
+
+// Function to load KTX texture using libktx
+    bool load_ktx_with_libktx(const std::string& filename, GLuint& textureID, GLenum& target, int& width, int& height) {
```
Comment (wba6) [inline Agate/src/Agate/Rendering/OpenGl/Texture.cpp]: Does this work?

File: Agate/src/Agate/Rendering/ModelLoader.cpp (hunk 4 above)
Comment (wba6) [reply Agate/src/Agate/Rendering/ModelLoader.cpp]: I could not locate a less expensive way to convert this

File: Agate/src/Agate/Rendering/ModelLoader.h
Comment (wba6) [inline Agate/src/Agate/Rendering/ModelLoader.h:1]: Need comments in this file
